### ISSUE TITLE
Bluemix K8S的技术架构问题？

### ISSUE THREAD

**Issue by krast** [alix2013/Bluemix-kubernetes-handson-lab#1]
Bluemix K8S是怎么增强为企业服务的？网络架构上是用的fannel还是OVN，openvpn在bluemix k8s里到底是做什么用的。

**Comment by alix2013** [comment]
Bluemix K8S用的网络组件是Calico, openvpn主要实现worker node和master之间的安全通信，Bluemix的K8S可以和 Cloud Foundry Base的Service很好的集成，企业中那些不适合或者不方便容器做的事可以通过 Cloud Foundry Base的Service去完成， Bluemix已经有的丰富的Service可以满足企业各类需要，同时用与不用这些Service都不是强制的，企业可以按需选择。

**Comment by alix2013** [comment]
close it
